Change the way the osx installer is created
Mudlet/installers pull request #1
Opened 2017-03-15 22:04 UTC by keneanung

It is now possible to create a dmg (osx installer image) from a pre-compiled
Mudlet.app. The script will also install all run time dependencies and copy them
into the app bundle creating the dmg.

Building and packaging mudlet is still possible by using the new
build-and-make-installer.sh. This requires a "commit-ish" now to be more
flexible about what will be built/packaged.

I also put the appdmg files into this project because they are installer files.

2017-03-15 22:05 UTC, keneanung commented
This is _not_ ready yet. I'm missing the documentation

2017-03-16 21:01 UTC, keneanung commented
I added a documentation that should explain the process, usage of the scripts.

The whole thing was also tested using a clean VM with only brew and XCode installed.

2017-03-17 11:56 UTC, vadi2 requested changes
Nice, thanks! Pretty much there, just a few minor tweaks.

2017-03-17 11:56 UTC, vadi2 commented on osx/build-and-make-installer.sh
> +mkdir build
Could you add an ``rm -rf`` before it - script stops and fails if this exists.

2017-03-17 11:56 UTC, vadi2 commented on osx/appdmg/mudlet-appdmg.json
> +{
Could you submit a corresponding PR to ``development`` to take these installer-related files out?

2017-03-17 11:56 UTC, vadi2 commented on osx/README.md
> +### Generating the installer ###
I would  clarify the title to "Generating the installer only"

2017-03-17 11:56 UTC, vadi2 commented on osx/make-installer.sh
> +sudo luarocks-5.1 install LuaFileSystem
Could you move the luarocks install to be at the top, so the script asks you for the sudo password once at the start and then you can look away?

2017-03-17 11:56 UTC, vadi2 commented on osx/make-installer.sh
> +npm install -g appdmg
On macOS < 10.12.3, https://github.com/LinusU/node-appdmg/issues/121 hits us - I had to patch ``appdmg`` with https://github.com/ArmorText/node-appdmg/commit/17dfeebdf01d42f519a77e6f43d4008cfb7dc3c7 to get the background to show.

Could you add a check for the version and apply the patch?

2017-03-19 22:34 UTC, keneanung commented on osx/appdmg/mudlet-appdmg.json
> +{
Done, see Mudlet/Mudlet#428

2017-03-22 05:48 UTC, vadi2 commented
Is this ready for review again?

2017-03-22 15:17 UTC, keneanung commented
Yes, sorry I forgot about saying that

2017-03-23 21:59 UTC, vadi2 approved these changes
Seems to be pretty much there! I'll approve it so you can merge after fixing: Mudlet version says 3.0.0-*dev*-sha1 which doesn't line up with the build echo, and an additional req - could you also name the .dmg with Mudlet-$VERSION.dmg? Maybe even the application name so it can be installed side-by-side with the final "Mudlet"?

2017-03-24 08:23 UTC, keneanung commented
> Mudlet version says 3.0.0-dev-sha1 which doesn't line up with the build echo

I actually left it intentionally at `dev` when you call `build-and-make-installer.sh`, because this allows us to differentiate between local builds (possibly with changes, named `dev`) and CI builds (named `testing`). Travis sets the version with `Ci/travis.set-build-info.sh`.

>  could you also name the .dmg with Mudlet-$VERSION.dmg

Sure!

> Maybe even the application name so it can be installed side-by-side with the final "Mudlet"?

I'll have to look into that. It may need more changing of the `src.pro` file than is currently done.

That gave me a thought, actually... Changing the application build multiple times (from multiple builds in a row) might mess it up very badly... Need to look into this.

2017-03-24 08:51 UTC, vadi2 commented
Ah ok, the intentional part is good then!

On Fri, Mar 24, 2017 at 9:23 AM keneanung <notifications@github.com> wrote:

> Mudlet version says 3.0.0-dev-sha1 which doesn't line up with the build
> echo
>
> I actually left it intentionally at dev when you call
> build-and-make-installer.sh, because this allows us to differentiate
> between local builds (possibly with changes, named dev) and CI builds
> (named testing). Travis sets the version with Ci/travis.set-build-info.sh.
>
> could you also name the .dmg with Mudlet-$VERSION.dmg
>
> Sure!
>
> Maybe even the application name so it can be installed side-by-side with
> the final "Mudlet"?
>
> I'll have to look into that. It may need more changing of the src.pro
> file than is currently done.
>
> That gave me a thought, actually... Changing the application build
> multiple times (from multiple builds in a row) might mess it up very
> badly... Need to look into this.
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Mudlet/installers/pull/1#issuecomment-288960966>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAGxjDf-EfvDXwJscg3fcGiDzPyBtW1Vks5ro32WgaJpZM4Melvl>
> .
>

2017-03-27 19:48 UTC, vadi2 approved these changes
Works great! Thanks so much for working through it!

2017-03-27 19:53 UTC, keneanung commented
Do you want the version in the `plist` as part of this PR or should I merge it in (I still want to squash some fixmes) and do the version stuff in an extra PR?

2017-03-27 20:03 UTC, vadi2 commented
Ah yeah, feel free to add the plist changes in and merge then.

2017-03-27 20:32 UTC, keneanung commented
I added a first version for the plist version part, but it's not tested yet!

2017-03-28 21:04 UTC, keneanung commented
This should be _finally_ good to go if I didn't forget any of the additional ideas we got :stuck_out_tongue:

2017-03-28 21:27 UTC, vadi2 commented
Cool! Would you like this to be a merge commit or a squash?

2017-03-29 19:13 UTC, keneanung commented
A merge commit should be good enough. I squashed as much as possible and reordered some commits, so the current commit history is how the feature came to be.

2017-03-29 19:14 UTC, merged